config/routes.rb
Rails.application.routes.draw do
  resources :follows
  ActiveAdmin.routes(self)
  get 'homes/index'
  
  resources :assignments do
    post "follow", to:"users#follow"
    member do
        put "like", to: "assignments#like"
        put "unlike", to: "assignments#unlike"
    end
  end

  resources :tags
  resources :categories
  resources :comments
  
  root "assignments#index"
  resources :assignments
  get "/ideas" => "assignments#index"
  post "/create_comment_ajax" => "comments#create_comment_ajax"
  get "/comments" => "comments#index"
  get "/contributions" => "users#contributions"
  get "/more_comments/:id" => "comments#more_comments", :as => "more_comments"
  get "/public/:id" => "users#public_profile"
  get "/search" => "assignments#search"
  get "/fresh_page_view/:id" => "comments#fresh_page_view", :as => "fresh_page_view"
  get "/liked_by/:id" => "users#liked_by" , :as => "liked_by"
  get "/notify_me" => "users#notify_me"
  get "/search_by_category" => "users#search_by_category"
  
  resources :users do
    post "follow", to:"users#follow"
  end  
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  

  

  

 

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

	belongs_to :user
	has_many :tags
	belongs_to :category
  #has_many :comments
  attr_accessor :rank

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", home: "620x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/ 
  

  has_attached_file :document
  validates_attachment_content_type :document, :content_type => ["application/pdf","application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "text/plain"]
  
  validates :title, presence: true
  validates :description, presence: true

  attr_accessor
	acts_as_commentable
        acts_as_paranoid

    def count_likes
      likes = Like.where(assignment_id: self.id, status: true).count
    end  

    def count_unlikes
      unlikes = Like.where(assignment_id: self.id, status: false).count
    end  
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index

    if ((params[:tag].present? && params[:tag] == "popular") || (params[:List_by].present? && params[:List_by] == "Likes"))
      @popular_assignment1 = Assignment.where(status: false).all
      popular = {}
      s = []
      if params[:List_by].present? 
        for i in @popular_assignment1
          popular[i.id] = Like.where(Assignment_id: i.id,status: true).count
        end
        @listed_by = "Likes"
      else
        for i in @popular_assignment1
          popular[i.id] = (Comment.where(Assignment_id: i.id).all.count * 5) + Like.where(Assignment_id: i.id,status: true).count
        end
        @listed_by = "Popular List"
      end
      @popular_view1 = popular.sort_by{|_key, value| -value}.to_h
      p @popular_view1
      p "D"*100
      order_hsh = @popular_assignment1.group_by(&:id)
      # binding.pry
      @popular_view1.keys.each do |i|
        s << order_hsh[i].first
      end 
      @assignments = s
    elsif params[:List_by].present? && params[:List_by] != "Likes" 
      @assignments = Assignment.where(status: false, category: params[:List_by]).order(created_at: :desc)
      @listed_by = params[:List_by]    
    else 
      @listed_by = "List by"
      @assignments = Assignment.where(status: false).order(created_at: :desc) #change it to sort by published date. Show most recent on top
    end  
    @popular_assignment = Assignment.all
    @comments = Comment.all.group_by(&:assignment_id)
    @user = User.all
    @like_obj = Like.all
    @like_count = @like_obj.where(status: true).group(:assignment_id).count
    p @like_obj
    @unlike_count = @like_obj.where(status: false).group(:assignment_id).count
    @twocom = Comment.last(2)
    @com = Comment.new #hash
    popular = Hash.new
    @browse_color = 1


    likes= @like_obj.all.where(status: true).group_by(&:assignment_id)
    popular = Hash.new
    for i in @assignments
      p i.id
      p @comments[i.id]
      p "$"*100
      
      popular[i.id] = (@comments[i.id].count * 5) unless @comments[i.id].blank?

      popular[i.id] += likes[i.id].count unless likes[i.id].nil?
     
    end
    @popular_view = popular.sort_by{|_key, value| -value}.to_h
        p @popular_view

    # for i in @assignments
    #   popular[i.id] = (Comment.where(Assignment_id: i.id).all.count * 5) + Like.where(Assignment_id: i.id,status: true).count
    # end
    # @popular_view = popular.sort_by{|_key, value| -value}.to_h
    # p @popular_view
    # p "s"*100
    # @popular_view = @assignments[0..3] || []
     @popular_list = @assignments[4..8] || []
    render "idea_temp"
  end


  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
        @submit_color = 1

  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)
    @assignment.user_id = current_user.id
    Rails.logger.info "S"*100
    Rails.logger.info @assignments
    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def add_comments_to_assignment_post
    #params = {"id" => "", content => ""}
    post = Assignment.where(id: params[:id])
    if post.present?
      comment = post.comments.create
      post.content = params[:content]
      post.user_id = current_user.id
      post.save
      render :json => {success: "Thanks for commenting"}
    else
      render :json => {errors: "Post is no longer available"}
    end  
  end
     
  def like
  assign = Assignment.find(params[:id])
    if assign.present?
      @assign_id = assign.id
      like_obj = Like.where(assignment_id: assign.id, user_id: current_user.id).first
      if like_obj.blank?
        like_obj = Like.new
        like_obj.user_id = current_user.id
        like_obj.assignment_id = assign.id
      end
     
      if like_obj.status.to_s == params[:status]
        like_obj.status = nil
        @sta = 0
      else
        like_obj.status = params[:status]
        @sta = like_obj.status
      end 


      if like_obj.save 
          @likecount = Like.where(assignment_id: assign.id, status: true).count
          @unlikecount =  Like.where(assignment_id: assign.id, status: false).count
          # @sta = like_obj.status
p like_obj.status.class
p nil.class
p @sta.class
        # render json: { likes: assign.count_likes, id: params[:id], unlikes: assign.count_unlikes }=
        # format.js { render action: 'like', status: :created, location: @comment , locals: {assignment_id: assignment_obj}}
      else
        render json: {errors: like_obj.errors.full_messages}  
      end  
    end  
  end

  def search
    #put the search criteria here and try to reuse or combine the index method
    # @assignments = Assignment.where("description LIKE ?","%#{params[:query]}%").all.order(created_at: :desc)
    #@comments = Comment.all.group_by(&:assignment_id)
    #@twocom = Comment.last(2)
    #@com = Comment.new #hash
    @popular_assignment = Assignment.where(status: false)
    p @popular_assignment 
    p "D"*100
    @comments = Comment.all.group_by(&:assignment_id)
    @user = User.all
    @like_obj = Like.all
    @like_count = @like_obj.where(status: true).group(:assignment_id).count
    p @like_obj
    @unlike_count = @like_obj.where(status: false).group(:assignment_id).count
    @twocom = Comment.last(2)
    @com = Comment.new #hash
    query_value = params[:query] 
    p "2"*100
    if @user.where(name: params[:query]).present?
      @assignments = @popular_assignment.where(user_id: @user.where(name: params[:query]).first.id)
    else
     @assignments = @popular_assignment.find_by_sql("SELECT * FROM assignments
      WHERE deleted_at IS NULL AND title LIKE '%#{query_value}%' OR description LIKE '%#{query_value}%' AND deleted_at IS NULL
      ORDER BY CASE
        WHEN (title LIKE '%#{query_value}%' AND description LIKE '%#{query_value}%') THEN 1
        WHEN (title LIKE '%#{query_value}%' AND description NOT LIKE '%#{query_value}%') THEN 2
        ELSE 3
        END, title
    LIMIT 0, 6; ")
     end
     
     @query_value = query_value 
     p @assignments
     p "F"*100
     popular = Hash.new
     for i in @popular_assignment
       popular[i.id] = (Comment.where(Assignment_id: i.id).all.count * 5) + Like.where(Assignment_id: i.id,status: true).count
     end
    @popular_view = popular.sort_by{|_key, value| -value}.to_h
    p @popular_view
    p "s"*100
    @popular_list = @assignments[4..8] || [] 
    render "idea_temp"
  end  
  # DELETE /assignments/1
  # DELETE /assignments/1.json

  def popular

  end

  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def follow
    # idea_id, 
    Follow.create(user_id: current_user.id, obj_type: Follow::IDEA, obj_id: params[:assignment_id])
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      p params
      p "D"*100
      params.require(:assignment).permit(:description, :user_id, :category_id, :status, :avatar, :title, :quote, :document)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= simple_form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    
  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div> <br>

  <div class="field">
    <%= f.label :quote %>
    <%= f.text_area :quote %>
  </div> <br>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div> <br>

  <div class="field">
    <%= f.label :document %>
    <%= f.file_field :document%> 
  </div>

  <table>
  <tr>
  <td>
    <div class="field">
      <%= f.label :category_id %>
      <%= f.select :category_id, [['Technology'], ['Hospitality'], ['Education'], ['Sports']]  %>
    </div>
  </td>

  <td>
    <div class="field">
      <%= f.label :status %>(Make Private)
      <%= f.check_box :status %>
    </div>
  </td> 
  <td>
    <div class="field">
      <%= f.input :avatar, as: :file %>
    </div>
  </td>
  </tr>
  </table>
  <br>
  <div class="actions">
    <input type="submit" value="Submit idea" name="commit"></input>
  </div>
  
<% end %>


<!-- <%= simple_form_for @assignment, defaults: { input_html: { class: 'default_class' } } do |f| %>
  <%= f.input :description, input_html: { class: 'special' }, as: :text %>
  <%= f.input :category_id, as: :select,  input_html: { value: 'Category'} %>
  <%= f.input :status, as: :radio_buttons, input_html: { value: 'Make Private'} %>
  <%= f.input :avatar, as: :file %>
  <%= f.button :submit %>
<% end %> -->

app/views/assignments/edit.html.erb
<div id="main" >
<h1>Editing Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>
</div>

app/views/assignments/idea_temp.html.erb
<div id="main">
<% ideas = @assignments %>
<% if ideas.present? %>
  <% @assignments.each do |post| %>
      <article class="post">
        <header>
          <div class="title" style="padding-top: inherit; margin-top: 10px; margin-left: 20px; margin-bottom: 0px; padding: inherit;">
            <h2><a href="#"> <%= post.title %> </a></h2>
            <p><%= post.quote %></p>
          </div>

          <div class="meta">
            <time class="published" datetime="<%= post.created_at.strftime("%d-%m-%Y")%>"><%= post.created_at.strftime("%B %d, %Y") %></time>
        <% p post %>
        <% p "d"*100 %>
            <a href="/public/<%= post.user.id %>" class="author"><h2 class="name"><%= post.user.name ||= post.user.get_display_name %></h2><img src="<%= post.user.avatar.url(:medium) %>" alt=""  /></a>
          </div>
        </header>
        <% if !post.avatar.blank? %>
            <div style="margin-left:100px;margin-right:100px; overflow:hidden;" >
              <a href="#" class="image featured"><img src="<%= post.avatar.url(:original) %>" alt="" width="600px" height="400px"/> </a>
            </div>
        <% end %>
        <p><%= post.description[0..300] %>.....</p>

        <% if !post.document.blank? %>
            <a href=<%= post.document(:original) %>><%= image_tag("Iconpdf.png") %></a>
        <% end %>



        <footer>
          <ul class="actions">
            <li ><a href="fresh_page_view/<%=post.id%>" class="button big" style="color:red">
              Continue Reading</a></li>
          </ul>
          <ul class="stats">
            <li> <%= post.category_id %></li>
            <% if !@like_obj.where(assignment_id: post.id, user_id: current_user.id).blank? %>
                <% likepic,unlikepic = case @like_obj.where(assignment_id: post.id,user_id: current_user.id).first.status
                                         when true
                                           ["thumbs-up","empty_thumbs-down"]
                                         when false
                                           ["empty_thumbs-up","thumbs-down"]
                                         when nil
                                           ["empty_thumbs-up","empty_thumbs-down"]
                                       end %>
                <% like_count = @like_count[post.id.to_s].to_i
                   unlike_count = @unlike_count[post.id.to_s].to_i %>
            <% elsif !@like_obj.where(assignment_id: post.id).blank? %>
            	<% like_count = @like_count[post.id.to_s].to_i
                   unlike_count = @unlike_count[post.id.to_s].to_i 
                   likepic,unlikepic = ["empty_thumbs-up","empty_thumbs-down"] %>
            <% else %>
            	  <% like_count = 0
                   unlike_count = 0
                   likepic,unlikepic = ["empty_thumbs-up","empty_thumbs-down"] %>
            <% end %>
            <li class="like-count" id="like-<%= post.id %>">
              <%= like_count %>
            </li>
            <li id="likepic-<%= post.id %>">
              <%= link_to image_tag(likepic), like_assignment_path(post,status: true),  class: 'vote', method: :put, remote: true %>
            </li>
           <!--  <li class="unlike-count" id="unlike-<%= post.id %>">
              <%= unlike_count %>
            </li> -->
            <!-- <li id="unlikepic-<%= post.id %>">
              <%#= link_to image_tag(unlikepic), like_assignment_path(post,status: false), class: 'vote', method: :put , remote: true  %>
            </li> -->
            <!-- <li><a href="#" class="icon fa-heart">28</a></li> -->
            <% if !@comments[post.id].blank?
                 comment_count = @comments[post.id].count
               else
                 comment_count = 0;
               end %>
            <li><a href="#comment_table" > <%= comment_count %></a>
              <%= link_to image_tag("comment.png"), fresh_page_view_path(post.id)  %>
            </li>
          </ul>
        </footer>
        <div>

          <% if @comments[post.id] !=nil %>
              <% comments_detail = @comments[post.id].last(2) %>
              <%#= raise comments_detail.inspect %>
              <%# all_comment = {} %>
              <%# comments_detail.map {|u| all_comment[u.id] = u.content} %>
              <%= render partial: 'comments/assgn_comment', locals: {comment: comments_detail ,assignid: post.id} %>
          <% end %>
          <%= render partial: 'comments/new_comment_form', locals: { assignid: post.id} %>
        </div>
      </article>
  <% end %>
  <% else %>
  <h2>No Ideas Listed for the search <%= @query_value %></h2>
  <% end %>

  <!-- Pagination -->
 <!--  <ul class="actions pagination">
    <li><a href="" class="disabled button big previous">Previous Page</a></li>
    <li><a href="#" class="button big next">Next Page</a></li>
  </ul> -->

</div>

<!-- Sidebar -->
<section id="sidebar">

  <!-- Intro -->
  <section id="intro">
    <a href="#" class="logo" style="display: -moz-box;width: 200px;height: 200px;"><img src="/assets/ideatree.jpg" alt="" /></a>
    <header>
      <h2>Ideatree</h2>
      <p>The place where ideas collide and shape up</a></p>
    </header>
  </section>

  <!-- Mini Posts -->
  <section>
    <div class="mini-posts">

      <article class="mini-post">
        <header >
          <h2 style="back-ground-color: #ff0000;"><a href="?tag=popular">Popular posts</a></h2>
        </header>
      </article>
      <div class="field" style="width:200px">
      <form action="/assignments" method="get">               
      <select id="list_by" name="List_by">
      <option value=""><%= @listed_by %></option>
      <option value="Technology">Technology</option>
      <option value="Hospitality">Hospitality</option>
      <option value="Sports">Sports</option>
      <option value="Education">Education</option>
      <option value="Likes"> Likes</option>

      </select> 
      <input name="commit" type="submit" value="Search" class="action" />
      </form></div>
      <% @popular_view.each do |k,v| %>
          <% post = @popular_assignment.where(id: k).first %>
          <article class="mini-post">
            <header>
              <h3><a href="fresh_page_view/<%=post.id%>"><%= post.title %></a></h3>
              <!-- Update created_at with published at -->
              <time class="published" datetime="<%= post.created_at.strftime("%d-%m-%Y")%>"><%= post.created_at.strftime("%B %d, %Y") %></time>
              <a href="/public/<%= post.user.id %>" class="author"><img src="<%= post.user.avatar.url(:original) %>" alt="" /></a>
            </header>
            <a href="#" class="image"><img src="<%= post.avatar.url(:medium) %>" alt="" /></a>
          </article>
      <% end %>

    </div>
  </section>

  <!-- Posts List -->
  <section>
    <ul class="posts">
      <% @popular_list.each do |post| %>
          <li>
            <article>
              <header>
                <h3><a href="#"><%= post.title %></a></h3>
                <time class="published" datetime="2015-10-20"><%= post.created_at.strftime("%B %d, %Y") %></time>
              </header>
              <a href="/public/<%= post.user.id %>" class="image"><img src="<%= post.avatar.url(:medium) %>" alt="" /></a>
            </article>
          </li>
      <% end %>
    </ul>
  </section>

  <%= render :partial => "layouts/about" %>
  <%= render :partial => "layouts/footer" %>


</section>
<!-- Scripts -->

app/views/assignments/index.html.erb
<p id="notice"><%= notice %></p>
<h1 style="margin-left:20%">Listing Ideas</h1>
<%#= render :partial => "shared/home_nav_bar" %>
<div style="margin-left:20%;width:900px; border-style: outset; box-shadow: 0 2px 4px 0 rgba(0,0,0,0.50),0 2px 10px 0 rgba(0,0,0,0.18) !important;" >
        
    <div style="margin-left:10%;margin-top:50px; width:200px,display:table">

        <table border="2" >
    

            <% @assignments.each do |assignment| %>
                <tr>
                    <div style="font-size:20px;margin-top:50px ; width:620px; float:left;">
                        <%= assignment.user_id %>
                    </div> 

                    <% if user_signed_in? && current_user.id == assignment.user_id %>
                    <div style="width:40px; float: right; margin-top:50px">
                        <%= link_to image_tag("edit.png", :size => "15x15"),edit_assignment_path(assignment) %>

                    
                        <%= link_to image_tag("delete.png", :size => "15x15"),assignment, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                    <% end -%>
                </tr>
                    <br>

               
                <br>
                <br>
                <tr>
                    <%# if File.exist?(assignment.avatar.url) %>
                    <%= image_tag assignment.avatar.url %>
                    <%#end%>
                </tr> 
                <br>
                  <tr> 
                  <div>
                  <%#= image_tag @user.where(:id => assignment.id).first.avatar_file_name.url, :size => "100x100" %>
                  </div>
                    <div style="font-size:20px;float:left;width:600px">
                        <%= assignment.description %>
                    </div>
                </tr>
                    <br>
              <br><br>

                <tr>Category = <%= assignment.category_id %></tr>
                <br>
                <tr>


                    <% if !@like_obj.where(assignment_id: assignment.id, user_id: current_user.id).blank? %> 
                        <% likepic,unlikepic = case @like_obj.where(assignment_id: assignment.id,user_id: current_user.id).first.status 
                            when true
                                ["thumbs-up","empty_thumbs-down"]
                            when false
                                ["empty_thumbs-up","thumbs-down"]
                            when nil
                                ["empty_thumbs-up","empty_thumbs-down"]
                            end %>
                        <% like_count = @like_count[assignment.id.to_s]
                            unlike_count = @unlike_count[assignment.id.to_s] %>
                   
                    <% else %>
                        <% like_count = 0
                            unlike_count = 0
                            likepic,unlikepic = ["empty_thumbs-up","empty_thumbs-down"] %>
                    <% end %>

                    <div class="like-count" id="like-<%= assignment.id %>">
                    <%= like_count %>  
                    </div>
                    <div id="likepic-<%= assignment.id %>">
                    <%= link_to image_tag(likepic), like_assignment_path(assignment,status: true),  class: 'vote', method: :put, remote: true %>
                    </div>
                    <br>

                   <div class="unlike-count" id="unlike-<%= assignment.id %>">
                    <%= unlike_count %>
                    </div>
                    <div id="unlikepic-<%= assignment.id %>">
                    <%= link_to image_tag(unlikepic), like_assignment_path(assignment,status: false), class: 'vote', method: :put , remote: true  %>
                   </div>
                </tr>
                <br>
                <tr>
                <% if @comments[assignment.id] !=nil %>
    <% all_comment = @comments[assignment.id] %>
   <% all_comment =  all_comment.reverse.map(&:content) %>
                     <%= render partial: 'comments/assgn_comment', locals: {all_comment: all_comment ,assignid: assignment.id} %>

      <% end %>
                <tr>
                <%= render partial: 'comments/new_comment_form', locals: { assignid: assignment.id} %>

                
                </tr>
                

                <% if user_signed_in? && current_user.id == assignment.user_id %>
                <tr>
                </tr>
                
                <br>
                <% end %>
            <% end %>
        </table>
    </div>
</div>

app/views/assignments/like.js.erb
console.log("#{<%=@likecount%>}");
console.log("#{<%=@unlikecount%>}");
$("#like-<%=@assign_id%>").html("<%=@likecount%> ");
$("#unlike-<%=@assign_id%>").html("<%=@unlikecount%>");

switch(<%= @sta %>) {
    case true:
        likepic = "http://localhost:3000/assets/thumbs-up.png"
        unlikepic = "http://localhost:3000/assets/empty_thumbs-down"
        break;
    case false:
        likepic = "http://localhost:3000/assets/empty_thumbs-up"
        unlikepic = "http://localhost:3000/assets/thumbs-down"
        break;
    default:
        likepic = "http://localhost:3000/assets/empty_thumbs-up"
        unlikepic = "http://localhost:3000/assets/empty_thumbs-down"
}


$("#likepic-<%=@assign_id%> a img")[0].src = likepic
$("#unlikepic-<%=@assign_id%> a img")[0].src = unlikepic




// escape_javascript

app/views/assignments/new.html.erb
<div id="main" >
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>
</div>

app/views/assignments/show.html.erb
<div id="main" >
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @assignment.description %>
</p>

<p>
  <img src="<%= @assignment.avatar.url(:medium) %>" alt="" />
</p>


<p>
  <strong>User:</strong>
  <%= @assignment.user_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @assignment.category_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @assignment.status %>
</p>

    
<% if user_signed_in? && current_user.id == @assignment.user_id %>
	<%= link_to 'Edit', edit_assignment_path(@assignment) %>  |
	<%= link_to 'Back', assignments_path %>

<% end -%>

	
</p>
</div>