config/routes.rb
Rails.application.routes.draw do
  resources :follows
  ActiveAdmin.routes(self)
  get 'homes/index'
  
  resources :assignments do
    post "follow", to:"users#follow"
    member do
        put "like", to: "assignments#like"
        put "unlike", to: "assignments#unlike"
    end
  end

  resources :tags
  resources :categories
  resources :comments
  
  root "assignments#index"
  resources :assignments
  get "/ideas" => "assignments#index"
  post "/create_comment_ajax" => "comments#create_comment_ajax"
  get "/comments" => "comments#index"
  get "/contributions" => "users#contributions"
  get "/more_comments/:id" => "comments#more_comments", :as => "more_comments"
  get "/public/:id" => "users#public_profile"
  get "/search" => "assignments#search"
  get "/fresh_page_view/:id" => "comments#fresh_page_view", :as => "fresh_page_view"
  get "/liked_by/:id" => "users#liked_by" , :as => "liked_by"
  get "/notify_me" => "users#notify_me"
  get "/search_by_category" => "users#search_by_category"
  
  resources :users do
    post "follow", to:"users#follow"
  end  
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  

  

  

 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :assignment 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  before_action :find_assignment_and_comment, :only => [:create, :create_comment_ajax]
  def index
    @user = User.all
    @comments = Comment.all
    @all_comments = @comments
    @all_assignment = Assignment.where(status: false)
    @assignment = @all_assignment.find(params[:format])
    @comment = @comments.new
    render "fresh_page_view"
  end
  
  def fresh_page_view
    @assignment_obj = Assignment.where(status: false)
    if params["fresh"].present?
      list = @assignment = @assignment_obj.where(status: true).map(&:id)
    end 
    @next_page = @assignment_obj.all.map(&:id).index(params[:id].to_i)
    @next_page = @assignment_obj.all.map(&:id)[@next_page-1]
    @previous_page = @assignment_obj.all.map(&:id).index(params[:id].to_i)
    @previous_page = @assignment_obj.all.map(&:id)[@previous_page+1]
    @assignment = @assignment_obj.where(id: params[:id]).first
    @comments = Comment.where(assignment_id: @assignment.id).all
    @like_obj = Like.where(assignment_id: @assignment.id)
    @like_count = Like.where(status: true).where(assignment_id: @assignment.id).count
    p @like_obj
    @unlike_count = Like.where(status: false).where(assignment_id: @assignment.id).count
    @com = Comment.new #hash 
  end  
  # GET /comments/1
  # GET /comments/1.json
  def show
  end

#s = 5
  # GET /comments/new
  def new
    @comment = Comment.new
    @comment.assignment_id = params[:format]
    p "#"*100
    p params
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    # params = {content: "gfgf", assignment_id: 123}
    #redirect_to @comment, notice: 'Comment was successfully created.'
  end
  
  def create_comment_ajax
    assignment_obj = Assignment.find(params[:assignment_id])

      respond_to do |format|
      if @comment.save
        
        format.js { render action: 'show', status: :created, location: @comment , locals: {assignment_id: assignment_obj}}
      else
        format.js { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end  

  def find_assignment_and_comment
    assignment_obj = Assignment.find(params[:assignment_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.assignment_id = assignment_obj.id
    @comment.save
  end 


  def more_comments
    @assignment_obj = Assignment.find(params[:id])
    @com = Comment.where(assignment_id: @assignment_obj).reverse.drop(2).map(&:content)
  end  
  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    comment = Comment.find(params[:id])
    ass_id = comment.assignment_id
    comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_path(ass_id)}

    #   format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
     # @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_assgn_comment.html.erb
<%# if all_comment != nil %>
<%# if all_comment.count > 2 %>
<%#= link_to "MORE", more_comments_path(assignid),method: :get, remote: true%>

<%#= link_to 'More Comments', fresh_page_view_path(assignid) %>
 <%# end%>

 <div>
    <table id='comment_table-<%= assignid%>'>
     
	  <tbody id="comment-modal">
             <% comment.each do |comment| %>
	     <tr>
                 <td>
                  <div style="width: 100%; height: 100%; overflow: hidden;">
                      <div style="float:left; overflow:hidden;" >
                         <a href="#" ><img src="<%= comment.user.avatar.url(:original) %>" alt="" height="42" width="42"/></a>
                      </div>
                      <div style="margin-left:80px">
                      <p style='margin:0px !important;font-size: 1em;  '><%= comment.content %></p>
                       <p style="color:red;margin:0px;font-size: 0.8em;font-style:italic;">Posted by <%= comment.user.name ||= current_user.get_display_name %> <%= time_ago_in_words(comment.created_at) %> ago </p>
                       </div>
                  </div>
                   <% if current_user.id == comment.user_id %>
                       <td style="width:*;"><%= link_to image_tag("delete.png") , comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                   <% end %>
                   </td>
                   </tr>
                   <% end %>
	  </tbody>
	</table>
<%# end %>

app/views/comments/_form.html.erb
<% p comment %>
<% p "*"*100 %>
<%= form_for @comment do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
    <%#= hidden_field_tag 'assignment_id', assignment.id  %> 
  </div>
  <div class="actions">
    <%= f.submit %>
           <%# @comment.user_id = current.used_id %>

    
  </div>
<% end %>

app/views/comments/_new_comment.html.erb
<tr>
<td> 
 <div style="width: 100%; height: 100%; overflow: hidden;">
                      <div style="float:left; overflow:hidden;" >
                         <a href="#" ><img src="<%= comment.user.avatar.url(:original) %>" alt="" height="42" width="42"/></a>
                      </div>
                      <div style="margin-left:80px">
                      <p style='margin:0px !important;font-size: 1em;  '><%= comment.content %></p>
                       <p style="color:red;margin:0px;font-size: 0.8em;font-style:italic;">Posted by <%= comment.user.name ||= current_user.get_display_name %> <%= time_ago_in_words(comment.created_at) %> ago </p>
                       </div>
                  </div>
</td>
</tr>

app/views/comments/_new_comment_form.html.erb
<%= form_for(@com, remote: true, url: create_comment_ajax_url) do |f| %>

	<div class="field" >
	  	<%= f.label :comment_here %>
  		<%= f.text_field :content, :id => "com" %><br />

  	</div>
  	<div class="actions">
		<%= submit_tag  onSubmit="Submit" %>
		    <%= hidden_field_tag 'assignment_id', assignid %> 
		   <script type="text/javascript">
		   </script>
	</div>
<% end %>

app/views/comments/_save.js.erb
$("ul.errors").html("")
<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".comment-index").html("<%= escape_javascript(render 'index') %>")
  $("#comment-modal").modal("hide")
<% end %>

app/views/comments/_table_row.html.erb
<% commentdisplay.each do |comment_id, comment_content| %>
	 <tr>
	 	<td>
	 		<!-- User.where(id: Comment.where(id: k).first.user_id).first.name -->
	 		<%= p @all_comments.inspect %>
	        <%#=  p @user.where(id: @comments.where(id: comment_id).first.user_id).first.name %>
	    </td>
		<td> 
			<div style="background:#f1f1f1;width:600px; border-style: outset; box-shadow: 0 2px 4px 0 rgba(0,0,0,0),0 2px 10px 0 rgba(0,0,0,0.18) !important;" >  
				<%= comment_content %> 
			</div>
		</td>
	</tr>
<% end %>
 <!--  <#% if current_user.id.to_s == comment.user_id.to_s %>
	         <td><%#= link_to 'Like', like_path(comment) %></td> 
	        <td><%#= link_to 'Edit', edit_comment_path(comment) %></td>
	        <td><%#= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	        <%#end%>
</tr>	 -->

app/views/comments/create_comment_ajax.js.erb
alert("five four three");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/fresh_page_view.html.erb
<div id="main">
  <% post = @assignment %>
  <article class="post">
    <header>
      <div class="title">
        <h2><a href="#"><%= post.title %></a></h2>
        <p><%= post.quote %></p>
      </div>

      <div class="meta">
        <time class="published" datetime="<%= post.created_at.strftime("%d-%m-%Y")%>"><%= post.created_at.strftime("%B %d, %Y") %></time>
        <a href="/public/<%= post.user_id %>" class="author"><span class="name"><%= post.user.name ||= post.user.get_display_name %></span><img src="<%= post.user.avatar.url(:medium) %>" alt="" /></a>
      </div>
    </header>
    <div style="width: 100%; height: 100%; overflow: hidden;">
      <div style="float:left; overflow:hidden;margin-right: 50px " >
        <a href="#" class="image featured"><img src="<%= post.avatar.url(:original) %>" alt="" width="600px" height="400px" /></a>
      </div>
      <p><%= post.description %></p>
      <% if !post.document.blank? %>
          <a href=<%= post.document(:original) %>><%= image_tag("Iconpdf.png") %></a>
      <% end %>
    </div>
    <footer>
      <div>
        <ul class="stats">
            <li> <%= post.category_id %></li>
           <% if !@like_obj.where(assignment_id: post.id, user_id: current_user.id).blank? %>
                <% likepic,unlikepic = case @like_obj.where(assignment_id: post.id,user_id: current_user.id).first.status
                                         when true
                                           ["thumbs-up","empty_thumbs-down"]
                                         when false
                                           ["empty_thumbs-up","thumbs-down"]
                                         when nil
                                           ["empty_thumbs-up","empty_thumbs-down"]
                                       end %>
                <% like_count = @like_count
                   unlike_count = @unlike_count %>

            <% else %>
              <% like_count = @like_count
                   unlike_count = @unlike_count
                   likepic,unlikepic = ["empty_thumbs-up","empty_thumbs-down"] %>
            <% end %>
        
          <li class="like-count" id="like-<%= post.id %>">
            <%= like_count %>
          </li>
          <li id="likepic-<%= post.id %>">
            <%= link_to image_tag(likepic), like_assignment_path(post,status: true),  class: 'vote', method: :put, remote: true %>
          </li>

         <!--  <li class="unlike-count" id="unlike-<%= post.id %>">
            <%= unlike_count %>
          </li> -->
          <!-- <li id="unlikepic-<%= post.id %>">
            <%#= link_to image_tag(unlikepic), like_assignment_path(post,status: false), class: 'vote', method: :put , remote: true  %>
          </li> -->
        </ul>
      </div>
    </footer>
    <!-- <li><a href="#" class="icon fa-heart">28</a></li> -->
    <br>
    <div>
  <% if !@comments.blank? %>
          <table style="margin:5px" class='table' id='comment_table-<%= post.id%>'>
             <thead>
             <tr><th> <h3>Comments:</h3></th></tr>
             </thead>
             <tbody id="comment-modal">
             <% @comments.each do |comment| %>
                
                 <tr>
                 <td>
                  <div style="width: 100%; height: 100%; overflow: hidden;">
                      <div style="float:left; overflow:hidden;" >
                         <a href="#" ><img src="<%= comment.user.avatar.url(:original) %>" alt="" height="42" width="42"/></a>
                      </div>
                      <div style="margin-left:80px">
                      <p style='margin:0px !important;font-size: 1em;  '><%= comment.content %></p>
                       <p style="color:red;margin:0px;font-size: 0.8em;font-style:italic;">Posted by <%= comment.user.name ||= current_user.get_display_name %> <%= time_ago_in_words(comment.created_at) %> ago </p>
                       </div>
                  </div>
                   <% if current_user.id == comment.user_id %>
                       <td style="width:*;"><%= link_to image_tag("delete.png") , comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                   <% end %>
                   </td>
                   </tr>
             <% end %>
             </tbody>

           </table>
            <%# if @comments[post.id] !=nil %>
              <%# comments_detail = @comments[post.id] %>
              <%# all_comment = {} %>
              <%# comments_detail.map {|u| all_comment[u.id] = u.content} %>
              <%#= render partial: 'comments/assgn_comment', locals: {all_comment: all_comment ,assignid: post.id} %>
            <%# end %>
      <% end %>
                <%= render partial: 'comments/new_comment_form', locals: { assignid: post.id} %>

</article>

<!-- Pagination -->
<ul class="actions pagination">
  <% if @previous_page == nil %>
      <li><a href="" class="disabled button big previous">Previous Page</a></li>
  <% else %>
      <li><a href="<%= @previous_page %>" class="button big next">Previous Page</a></li>
  <% end %>
  <li><a href="<%= @next_page %>" class="button big next">Next Page</a></li>
</ul>

</div>

app/views/comments/index.html.erb
<%# raise @comments.where(assignment_id: @assignment.id).inspect %>

                    <% if user_signed_in? && current_user.id == @assignment.user_id %>
                    <div style="width:40px; float: right">
                        <%= link_to image_tag("edit.png", :size => "15x15"),edit_assignment_path(@assignment) %>

                    
                        <%= link_to image_tag("delete.png", :size => "15x15"),@assignment, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                    <% end -%>
               <br>
                    <%# if File.exist?(assignment.avatar.url) %>
                    <%= image_tag @assignment.avatar.url, :size => "400x300" %>
                    <%#end%>
               <br>
                    <div style="font-size:20px">
                        <%= @assignment.description %>
                    </div>
               <br> <div> Category = <%= @assignment.category_id %> </div>  <br>
                
                <% if @comments[@assignment.id] != nil %>
                    <div style="display:table;">
    <table style="margin:5px;" class='table' id='comment_table'>
    <thead>
      <tr>
        <th>Content</th>
      </tr>
    </thead>
    <tbody id="comment-modal">
      <% @comments.where(assignment_id: @assignment.id).each do |comment| %>
        
           <tr>
<td> 
<div style="background:#f1f1f1;width:600px; border-style: outset; box-shadow: 0 2px 4px 0 rgba(0,0,0,0),0 2px 10px 0 rgba(0,0,0,0.18) !important;" >  
 
<p><%= comment.content %></p>

 </td>

          <% if current_user.id.to_s == comment.user_id.to_s %>
          <td><%= link_to 'Like', edit_comment_path(comment) %></td>

          <%# raise comment.inspect%>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %> 
         </tr>
         </div>

      <% end %>
    </tbody>
  </table>
</div>

                <% end %>
                
                
                

                <% if user_signed_in? && current_user.id == @assignment.user_id %>
              
                    <%#= link_to 'Edit ', edit_assignment_path(assignment) %>
              
                
                <br>
                <% end %>
           



<script>
  var submitComment = function(){
      $.ajax(
        url: "/create_comment_ajax",
        method: post,
        //data: 1,
      data: {content: content, assignment: assign},
    success: function displayBackComment(){
           $("#comment-modal").append("content");
           $("#comment-modal").modal("content");

       }
     
     )};
</script>

app/views/comments/more_comments.js.erb
      

$('#comment_table-<%= @assignment_obj.id %>').append("<%= j render partial: 'table_row', locals: {comm: @com } %>");

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/show.js.erb
$('#comment_table-<%= assignment_id.id %>').append("<%= j render partial: 'new_comment', locals: {comment: @comment } %>");
$('#new_comment_modal').modal_success();
document.getElementById("com").value = "";

$('#com').val('');
$('#com').val('');