config/routes.rb
Rails.application.routes.draw do
  resources :follows
  ActiveAdmin.routes(self)
  get 'homes/index'
  
  resources :assignments do
    post "follow", to:"users#follow"
    member do
        put "like", to: "assignments#like"
        put "unlike", to: "assignments#unlike"
    end
  end

  resources :tags
  resources :categories
  resources :comments
  
  root "assignments#index"
  resources :assignments
  get "/ideas" => "assignments#index"
  post "/create_comment_ajax" => "comments#create_comment_ajax"
  get "/comments" => "comments#index"
  get "/contributions" => "users#contributions"
  get "/more_comments/:id" => "comments#more_comments", :as => "more_comments"
  get "/public/:id" => "users#public_profile"
  get "/search" => "assignments#search"
  get "/fresh_page_view/:id" => "comments#fresh_page_view", :as => "fresh_page_view"
  get "/liked_by/:id" => "users#liked_by" , :as => "liked_by"
  get "/notify_me" => "users#notify_me"
  get "/search_by_category" => "users#search_by_category"
  
  resources :users do
    post "follow", to:"users#follow"
  end  
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  

  

  

 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/  
  
  has_many :assignments      
  has_many :comments
  has_many :likes
  has_many :follows
  
  acts_as_paranoid

  validates_format_of :email, :with => /\A[\w+\-.]+@shoretel.com/i, :message => "Email is invalid, only Shoretel Email is allowed"

  attr_accessor :get_display_name

  def get_display_name
    #pry.bind
    name = self.name 
    name = self.first_name if name.blank?
    name = self.last_name if name.blank?
    name = self.email.split('@')[0]
  end 	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :show, only: [:notification_data]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @username_color = 1
    @all_user = User.all
    @like_obj = Like.all
    @like_count = @like_obj.where(status: true).group(:assignment_id).count
    @unlike_count = @like_obj.where(status: false).group(:assignment_id).count

        #@liked_by = User.where(id: @like_obj.where(status: true).map(&:user_id)).map(&:name)
    
    @liked_by = @like_obj.all.where(status: true).group_by(&:assignment_id)
    p "hiii"*20
    #p @liked_by["10"].first
    #p @unliked_by
    #@like_user_data = 
    # {1 => ["name1", "name2"]} like user
    @all_comments = Comment.all
  @users = User.all
  @all_likes = Like.all
  @assignment = Assignment.all
  @comment_array = []
  @like_array = []
  @comment_notify_hash = {}
  @like_notify_hash = {}
  j= 0
  k =0
  @assignment_id_array = @assignment.where(user_id: 4).map(&:id)
  for i in @assignment_id_array
    @comment = @all_comments.where(assignment_id: i)
    for k in @comment
      @comment_array[j] = k
      j= j+1
    end
  end
  j = 0
  for i in @assignment_id_array
    @like = @all_likes.where(assignment_id: i)
    for k in @like
      @like_array[j] = k
      j = j+1
    end
  end 
  j=0
  for i in @comment_array
    @comment_notify_hash[i.updated_at] = "<a href='/users/#{i.user_id}'>#{@users.where(id: i.user_id).first.name}</a>" +
    " commented on idea " + "<a href='/fresh_page_view/#{i.assignment_id}'>#{@assignment.where(id: i.assignment_id).first.title}</a>"
    j = j+1;
  end
  p @comment_notify_hash
  p "d"*100
  for i in @like_array
    @like_notify_hash[i.updated_at] = "<a href='/users/#{i.user_id}'>#{@users.where(id: i.user_id).first.name}</a>" +
    " likes your idea " + "<a href='/fresh_page_view/#{i.assignment_id}'>#{@assignment.where(id: i.assignment_id).first.title}</a>"
    j=j+1;
  end

   @notification_list = @like_notify_hash.merge(@comment_notify_hash).sort.reverse.to_h
    
    i = []
    j = 0
    @notify = 0
    @notification_list.each do |k,v|
        i[j] = k - @users.where(id: 4).first.current_sign_in_at
          if i[j]>0
            @notify = @notify+1
          end
        j = j+1
    end

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver_later
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def liked_by
    p params[:id]
    @assign_id =  params[:id]
    @like_obj = Like.all.where(assignment_id: params[:id])
    p @like_obj
    p "hiii"*20
    @liked_by = User.where(id: @like_obj.where(status: true).map(&:user_id)).map(&:name)
    @unliked_by = User.where(id: @like_obj.where(status: false).map(&:user_id)).map(&:name)
    p @liked_by
    p @unliked_by
       
end

def contributions
  @user = User.all
  @assignment = Assignment.all
  @contribution_color = 1
  @ideas = Assignment.where(status: false).group_by(&:user_id)
  @searched_by = "Search by category"

end

def search_by_category
  category = params[:search_by_category]
  p category
  @searched_by = category
  @ideas = Assignment.where(category: category, status: false).group_by(&:user_id)
  @user = User.all
  @contribution_color = 1
  render "contributions"

end

def public_profile
  @user = User.where(id: params[:id]).first
end

<<<<<<< HEAD
def notify_me
  current_user.update_attributes(notify_me: params[:checked])
  render nothing: true
end  

def notification_data
  #create hash of data with timestamps, follows, likes, comments
  @all_comments = Comment.all
  @users = User.all
  @all_likes = Like.all
  @assignment = Assignment.all
  @comment_array = []
  @like_array = []
  @comment_notify_hash = {}
  @like_notify_hash = {}
  j= 0
  k =0
  @assignment_id_array = @assignment.where(user_id: 4).map(&:id)
  for i in @assignment_id_array
    @comment = @all_comments.where(assignment_id: i)
    for k in @comment
      @comment_array[j] = k
      j= j+1
    end
  end
  j = 0
  for i in @assignment_id_array
    @like = @all_likes.where(assignment_id: i)
    for k in @like
      @like_array[j] = k
      j = j+1
    end
  end 
  j=0
  @comment_array.order(created: :desc)
  for i in @comment_array
    @comment_notify_hash[i.updated_at] = "<a href='/users/#{i.user_id}'>#{@users.where(id: i.user_id).first.name}</a>" +
    " commented on idea " + "<a href='/fresh_page_view/#{i.assignment_id}'>#{@assignment.where(id: i.assignment_id).first.title}</a>"
    j = j+1;
  end
  p @comment_notify_hash
  p "d"*100
  @like_array.order(created: :desc)
  for i in @like_array
    @like_notify_hash[i.updated_at] = "<a href='/users/#{i.user_id}'>#{@users.where(id: i.user_id).first.name}</a>" +
    " likes your idea " + "<a href='/fresh_page_view/#{i.assignment_id}'>#{@assignment.where(id: i.assignment_id).first.title}</a>"
    j=j+1;
  end

   @notification_list = @like_notify_hash.merge(@comment_notify_hash).sort.reverse.to_h


end  


def follow
  Follow.create(user_id: current_user.id, obj_type: Follow::USER, obj_id: params[:user_id])
end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    p params[:id]
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :phone, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.input :avatar, as: :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_liked_by.html.erb
<div data-role="main" class="ui-content">
  <% $next = 0 %>
     <% for i in liked_by %>
     <p> <%= i %> </p>
     <% $next += 1 %>
   <% end %>
  <a href="#" data-rel="back">Go Back</a>
</div>

app/views/users/_likedby_modal.html.erb
 <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <%= liked_by[0] %>
          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

app/views/users/contributions.html.erb
<div id="main">
<% i =0 %>
<%#= form_tag(contributions_user_path, method: 'put') do |f| %> 
   <%#= select_tag(:id, 
   options_for_select(@assignment.map{ |f| [f.category, i+=1]}), :prompt => "Select category") %> 
   <%#= submit_tag "Submit" %> 
<%# end %>

<!-- <div class="field" style="width:200px">
<form action="search_by_category" method="get">               
<select id="search_by_category" name="search_by_category">
<option value=""><%= @searched_by %></option>
<option value="Technology">Technology</option>
<option value="Hospitality">Hospitality</option>
<option value="Sports">Sports</option>
<option value="Education">Education</option>
</select> 
<input name="commit" type="submit" value="Search" class="action" />
</form></div> -->

  <% @user.each do |user| %>

  <% if @ideas[user.id].present? || @searched_by == "Search by category" %>
    <% var = rand(15) %>
	<div style="margin-left: 30px;margin-top:40px; width: 200px;border-style: outset; box-shadow: 0 2px 2px 0 rgba(0,0,0,0.10),0 2px 10px 0 rgba(0,0,0,0.18) !important; padding: 10px; float: left;background-color: <%= BGCOLOR[var] %>;" >

	<a href="/public/<%= user.id%>" class="author" ><img src="<%= user.avatar.url(:thumb) %>" alt=""  /></a>
	 <h2 class="name" href="<%= user.id%>" ><%= user.name ||= user.get_display_name %></h2> 
		<% if @ideas[user.id].present? %>
		  Total ideas : <%= @ideas[user.id].count %>  <br>
			<% @ideas[user.id].each do |idea| %>
				<% if !idea.title.blank?  %>
					<li style="margin-left:20px"><a href="/fresh_page_view/<%=idea.id%>"><span style="color: #25AAD5;"><%= truncate(idea.title.humanize, :length => 17, :separator => ' ') %>..</span></a></li>
				<% end %>
			<% end %>
	    <% else %>
	      No ideas submitted
	    <% end %>		
	</div>
	<% end %>
  <% end %>
</div>

app/views/users/dummy.html.erb
<div id="main">

 <% @user.each do |user| %>
<div style="margin-left: 30px;margin-top:40px; width: 200px;border-style: outset; box-shadow: 0 2px 2px 0 rgba(0,0,0,0.10),0 2px 10px 0 rgba(0,0,0,0.18) !important; padding: 10px; float: left" >

<a href="<%= user.id%>" class="author" ><img src="<%= user.avatar.url(:thumb) %>" alt=""  /></a>
 <h2 class="name" href="<%= user.id%>" ><%= user.name %></h2> 
Total ideas : <%= user.assignments.count %>  <br>
	<% user.assignments.each do |idea| %>
		<% if !idea.title.blank?  %>
			<li style="margin-left:20px"><%= idea.title.inspect %> </li>
		<% end %>
	<% end %>
</div>
<% end %>

</div>

app/views/users/edit.html.erb
<div id="main" >

<h1>Edit Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> 
<%#= link_to 'Back', users_path %>
</div>		

app/views/users/index.html.erb
<div id="main" >

<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email  %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
</div>

app/views/users/liked_by.js.erb
alert("#{<%=@liked_by%>}");

app/views/users/likedby.js.erb
//modal box
// open the modal..
$(".liked_by_users").html("<%=@liked_by%> ");


//has to go in some partial, add modal class from bootstrap
<html>
<div class="liked_by_users"></div>

</html>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/public_profile.html.erb
<head>
  <!--<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css"> -->
  <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
  <!--<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"> -->
  </script>
</head>

<div id="main" >
  <% ideas = @user.assignments.where(status: false) %>
  <% if ideas.present? %>
    <h2>Ideas by <%= @user.name ||=  @user.get_display_name %></h2>
    <table>
      <thead>
        <tr>
          <th></th>
          <th>Description</th>
          <th>Category</th>
          <th>View</th>
        </tr>
      </thead>

      <tbody>
        <% @user.assignments.where(status: false).each do |assignment| %>
          <tr>
            <td><%= image_tag assignment.avatar.url(:thumb), :size => "30x30" %></td>
            <td><%= assignment.description %></td>
            <td><%= assignment.category_id %></td>
            <td><a href="/fresh_page_view/<%=assignment.id%>"> Show </a></td>  
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h2>No Ideas Submitted By <%= @user.get_display_name %></h2>
    <div style="background-image: url('/assets/skull.jpg');"></div>
  <% end %>  
</div>
  

app/views/users/show.html.erb
<style>
.switch {
  position: relative;
  display: inline-block;
  width: 40px;
  height: 24px;
}

.switch input {display:none;}

.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 16px;
  width: 16px;
  left: 4px;
  bottom: 4px;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(16px);
  -ms-transform: translateX(16px);
  transform: translateX(16px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 24px;
}

.slider.round:before {
  border-radius: 50%;
}

a{
  font-weight: bold;
}



</style>

<!--<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css"> -->
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

<!--<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"> -->

<script language="javascript">
        
$(document).ready(function(){
  $('#cbSlide').on('change',function(){
    checked_status = $('#cbSlide').is(':checked');
  $.ajax({
      url: "/notify_me",
      data: {checked: checked_status},
      ContentType: 'application/json'
    });
});
});


$(document).ready(function(){
    $("#cbSlide").click(function(){
        $("#notificationLink").toggle();
        if ($('#cbSlide').is(':checked') == false) {
          $("#notificationLink").hide();
        } else
        {
          $("#notificationLink").show();
        }
      });
    });


</script>

<script>
$(document).ready(function(){
    $("#notification_list_show_hide").hide();
    $("#IdeasList").show();
    $("#notificationLink").show();
});

$(document).ready(function(){
    if ($('#cbSlide').is(':checked') == false) {
      $("#notificationLink").hide();
    } else
        {
          $("#notificationLink").show();
        }
});




$(document).ready(function(){
    $("#notificationLink").click(function(){
        $("#notification_list_show_hide").toggle();
        $("#IdeasList").toggle();

    });
});
</script>


<div id="main" >
<div id="NoNotification">
<%#= render :partial => "shared/home_nav_bar" %>
<div style="font-size:25px">
<b><a style="color: rgb(179, 36, 0);" href="/users/4/edit">Edit Profile</a></b>
 </div>
 
<% if @user.notify_me == true 
      checked= "checked"
    else
      checked = ""
    end %>

 <div style="font-size:20px">
<b style="top:5px">Notify me</b>
 <label class="switch" style="top:23px; margin-left:10px"  >
  <input type="checkbox" <%= checked %> id="cbSlide">
  <div class="slider round"></div>
</label>  </div>
</div>

  <a style="font-size:150%; font-weight: normal" id="notificationLink" href="#" >Notifications <span style="color:red"> (<%= @notify %>)</span></a> 

<div id="IdeasList">
<% ideas = @user.assignments.where(status: false) %>
<% if ideas.present? %>
  <h2>Ideas submitted by you</h2>

  <table>
    <thead>
      <tr>
        <th></th>
        <th>Description</th>
        <th>Category</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @user.assignments.each do |assignment| %>
        <tr>
          <td><%= image_tag assignment.avatar.url(:thumb), :size => "30x30" %></td>
          <td><%= assignment.description %></td>
          <td><%= assignment.category_id %></td>
          <td><%= assignment.status %></td>
          <td><a href="/fresh_page_view/<%=assignment.id%>"> Show </a></td>  
          <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
          <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%#= raise @like_obj.inspect %>
          <% if !@like_obj.where(assignment_id: assignment.id, user_id: current_user.id).blank? %> 

                                    <% likepic,unlikepic = case @like_obj.where(assignment_id: assignment.id,user_id: current_user.id).first.status 
                                        when true
                                            ["thumbs-up","empty_thumbs-down"]
                                        when false
                                            ["empty_thumbs-up","thumbs-down"]
                                        when nil
                                            ["empty_thumbs-up","empty_thumbs-down"]
                                      end %>
                                    <% like_count = @like_count[assignment.id.to_s].to_i
                                      unlike_count = @unlike_count[assignment.id.to_s].to_i %>
                                <% else %>
                                    <% like_count = 0
                                      unlike_count = 0
                                      likepic,unlikepic = ["empty_thumbs-up","empty_thumbs-down"] %>
                                <% end %>
          <td> <%= @like_count[assignment.id.to_s].to_i %></td>
          <td id="liked_by_<%=assignment.id%>"> <%= link_to image_tag(likepic), liked_by_path(id: assignment.id), :remote => true, :method => :get %>
          </td>

          <!-- <td><%= unlike_count %></td> -->
         <!--  <td><%#= link_to image_tag(unlikepic), like_assignment_path(assignment,status: false), class: 'vote', method: :put , remote: true  %>
          </td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
    <h2> No Ideas are submitted </h2>
<% end %>


  

  <!-- <div >

    <a href="#myPopupDialog" data-rel="popup" data-position-to="window" data-transition="fade" class="ui-btn ui-corner-all ui-shadow ui-btn-inline first34" id="<%#= 10  %>">Like</a>

    <div data-role="popup" id="myPopupDialog">
      <div data-role="header">
        <h1>Liked By</h1>
      </div>
      <div class="check123"><div data-role="main" class="ui-content">
  
  <a href="#" data-rel="back">Go Back</a>
</div>
</div>
    </div>  
  </div>
 -->

<%#= link_to 'Back', users_path %>

</div>
</div>
  
<div id="notification_list_show_hide" style="top:300px; left:300px; position:absolute; c" >

<%#= raise @notification_list.inspect %>
<% @notification_list.each do |k,v| %>
  <%= raw v %>  <p style="color:#6060ff;margin:0px;font-size: 0.8em;font-style:italic;"> <%= time_ago_in_words(k) %> ago </p> <br>
<% end %>
</div>